'use client';

import Link from 'next/link';
import { ArrowLeft, CalendarClock, MapPin, UserRound } from 'lucide-react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { SeverityIndicator, StatusBadge, TierBadge } from '@/components/ui';
import { useIncident } from '@/hooks/use-data';
import { apiClient } from '@/lib/api-client';
import type { Incident } from '@/types/api';

export default function IncidentPage({ params }: { params: { id: string } }) {
  const steps = ['OPEN', 'INVESTIGATING', 'DISPATCHED', 'MITIGATED', 'RESOLVED'];
  const query = useIncident(params.id); const client = useQueryClient(); const item = query.data; const currentIndex = item ? steps.indexOf(item.status) : 0;
  const transition = useMutation({ mutationFn: async (status: string) => (await apiClient.request<Incident>(`/incidents/${params.id}/status`, { method: 'PATCH', body: JSON.stringify({ status }) })).data, onSuccess: () => client.invalidateQueries({ queryKey: ['incident', params.id] }) });
  if (query.isLoading) return <div className="page-wrap"><div className="surface-panel h-64 animate-pulse"/></div>;
  if (!item) return <div className="page-wrap"><div className="surface-panel p-8 text-center text-slate-400">Incident could not be loaded.</div></div>;
  const next = steps[currentIndex + 1];
  return <div className="page-wrap max-w-6xl"><Link className="mb-5 inline-flex items-center gap-2 text-xs text-emerald-300 hover:text-emerald-200" href="/dashboard"><ArrowLeft size={14}/>Back to command center</Link><header className="page-header"><div><p className="page-eyebrow">Incident {item.id}</p><h1 className="page-title">{item.title}</h1><p className="page-description">{item.category.replaceAll('_', ' ')} · risk score {item.risk_score ?? 'pending'}</p></div><div className="flex gap-2"><SeverityIndicator severity={item.severity}/><StatusBadge status={item.status}/></div></header><div className="grid gap-5 lg:grid-cols-[1fr_320px]"><section className="surface-panel p-5 sm:p-6"><div className="flex items-center justify-between"><div><TierBadge tier="OBSERVED"/><h2 className="mt-3 font-semibold text-white">Lifecycle timeline</h2></div><CalendarClock className="text-slate-600"/></div><ol className="relative mt-7 space-y-0 before:absolute before:bottom-5 before:left-[15px] before:top-5 before:w-px before:bg-slate-800">{steps.map((step, index) => <li key={step} className="relative flex gap-4 pb-7 last:pb-0"><span className={`z-10 grid h-8 w-8 shrink-0 place-items-center rounded-full border text-xs font-bold ${index <= currentIndex ? 'border-emerald-400 bg-emerald-500 text-slate-950' : 'border-slate-700 bg-[#071521] text-slate-500'}`}>{index + 1}</span><div><p className={`text-sm font-medium ${index <= currentIndex ? 'text-white' : 'text-slate-500'}`}>{step}</p><p className="mt-1 text-xs text-slate-600">{index <= currentIndex ? 'Stage recorded by the incident service.' : 'Pending completion of the previous stage.'}</p></div></li>)}</ol></section><aside className="space-y-4"><section className="surface-panel p-5"><h2 className="font-semibold text-white">Incident details</h2><dl className="mt-4 space-y-4 text-xs"><div><dt className="flex items-center gap-1.5 text-slate-500"><MapPin size={13}/>Coordinates</dt><dd className="mt-1 text-slate-200">{item.location.latitude.toFixed(4)}, {item.location.longitude.toFixed(4)}</dd></div><div><dt className="flex items-center gap-1.5 text-slate-500"><UserRound size={13}/>Assigned officer</dt><dd className="mt-1 text-slate-200">{item.assigned_officer_id || 'Unassigned'}</dd></div></dl></section>{next && <button disabled={transition.isPending} onClick={() => transition.mutate(next)} className="primary-button w-full">Advance to {next}</button>}{transition.error && <p className="text-xs text-red-300">{transition.error.message}</p>}</aside></div></div>;
}
