from schemas.base import ApiResponse, PaginatedResponse, CoordinatesDTO, SpatialQueryFilter
from schemas.ai import (
    InformationTier,
    VerificationStatus,
    ConfidenceTier,
    PollutionCategory,
    AIExplanationSchema,
)
from schemas.entities import (
    UserRole,
    IncidentStatus,
    IncidentSeverity,
    AlertChannel,
    SensorType,
    UserRead,
    OrganizationRead,
    DataSourceRead,
    SensorRead,
    EnvironmentalObservationCreate,
    EnvironmentalObservationRead,
    CitizenReportCreate,
    CitizenReportRead,
    AIAnalysisRead,
    PollutionEventRead,
    PredictionRead,
    RiskAssessmentRead,
    AlertCreate,
    AlertRead,
    IncidentCreate,
    IncidentRead,
    VerificationCreate,
    VerificationRead,
    InterventionCreate,
    InterventionRead,
    InterventionMeasurementRead,
    AuditLogRead,
)
